title:            sebcachia.com
description:      Outdoor Freak and Allround Geek
logo:             site-logo.png
disqus_shortname: sebcachia
#Comment out url when working locally to resolve base urls correctly
#url:              http://sebcachia.com

# Owner/author information
owner:
  name:           Sebastian Cachia
  avatar:         avatar.png
  email:          me@sebcachia.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: sebcachia
  facebook: sebcachia
  github: sebcachia
  stackexchange:  
  linkedin: sebcachia
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/+sebastiancachia/ 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-3576414-1
google_verify: ZMG966sheYzavgwd15HsUDdRZ1-h3z1xouxDzXuF_pM
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:6CF7D1D4C3DD5952E1B5890419078C3D

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Tags
    url: /tags.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Malta
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]


search: true