# Site wide configuration

title: sebcachia.com
locale: en_US
description: Outdoor Freak and Allround Geek
logo: #
search: true
url: http://sebcachia.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sebastian Cachia
  avatar: avatar.png
  email: me@sebcachia.com
  disqus-shortname: sebcachia
  twitter: sebcachia
  facebook: sebcachia
  github: sebcachia
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: sebcachia
  instagram: sebcachia
  flickr: #
  tumblr: #username
  pinterest: #username
  google:
    plus: 
    analytics: UA-3576414-1
    verify: ZMG966sheYzavgwd15HsUDdRZ1-h3z1xouxDzXuF_pM
    ad-client:
    ad-slot: 
  bing-verify:
