# Site wide configuration

title:            sebcachia.com
locale:           en_US
url:              http://sebcachia.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Sebastian Cachia
  avatar: avatar.jpg
  bio: "Product person, Outdoor Freak and Allround Geek"
  email: me@ mydomain .com
  disqus-shortname: sebcachia
  twitter: sebcachia
  facebook: sebcachia
  google:
    plus: #username
    analytics: UA-3576414-1
    verify: ZMG966sheYzavgwd15HsUDdRZ1-h3z1xouxDzXuF_pM
    ad-client:
    ad-slot:
  bing-verify:
  github: sebcachia
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sebcachia
  xing: #username
  instagram: sebcachia
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
